Invitation
ProgramEngineeringOurJira/Backend pull request #10
Opened 2023-10-28 18:02 UTC by mimalakhov

Вопросы:
1. Как отличить неавторизованного пользователя от вообще не зарегистрированного? Я в обработчике запроса пишу user: User = Depends(get_current_user), но тогда я не могу увидеть, что пользователь вообще не зарегистрирован. get_current_user выбрасывает исключение, если не находит такого пользователя в таблице Users 
2. Как пользователь перейдёт на post запрос, если ему на почту приходит только ссылка? Я просто в get запросе его добавляю
3. Кто может отсылать приглашения - админ или все члены воркплейса?

2023-11-06 18:02 UTC, Nicialy commented
конфликты

2023-11-06 18:11 UTC, Nicialy requested changes

2023-11-06 18:11 UTC, Nicialy commented on app/core/email.py
> +    async def sendInvitationMail(self, request: Request, email: EmailStr, workplace_id: UUID, workplace_name: str):
в snake_case

2023-11-06 18:11 UTC, Nicialy commented on app/core/email.py
> +    async def sendRegistrationMail(self, request: Request, redis: Redis, user_register: UserRegister):
snake_case

2023-11-06 18:11 UTC, Nicialy commented on app/routers/workplace.py
> +async def add_to_workplace(workplace_id: UUID = Path(...), token: UUID = Depends(oauth2_scheme)):
У тебя есть get_current_user
И это все равно не будет работать, так как у тебя при переходе никто не цепляет токен

2023-11-06 18:11 UTC, Nicialy commented on app/routers/workplace.py
> +async def add_to_workplace(workplace_id: UUID = Path(...), token: UUID = Depends(oauth2_scheme)):
Что в итоге нужно создаешь рандомный uuid чел переходит:
 если ссылка отправлена на email в которой уже есть в системе добавляешь user в ворплейс
 если его нет в системе редиректишь на регистрацию

2023-11-08 18:37 UTC, Nicialy requested changes

2023-11-08 18:37 UTC, Nicialy commented on app/routers/workplace.py
> +        return RedirectResponse("/login")
registration и на константу из .env это на фронт пойдет

2023-11-08 18:37 UTC, Nicialy commented on app/routers/workplace.py
> +    return RedirectResponse(f"/workplaces/{workplace_id}")
тут тоже на константу из .env

2023-11-08 21:45 UTC, mimalakhov commented
Я не знаю что этому линту от меня надо, у меня всё ок
![2023-11-09_00-43-22](https://github.com/ProgramEngineeringOurJira/Backend/assets/94488402/6b59fb11-d570-404d-88b6-b8b327a0d49a)

2023-11-09 04:49 UTC, Nicialy commented
Ты не закомитил  тебе pre-commit in job  хочет изменить файлы

2023-11-09 04:49 UTC, Nicialy commented
там написан окакой файл reformatted app/routers/workplace.py

2023-11-09 11:30 UTC, mimalakhov commented
Я запускал pre-commit перед обоими коммитами, но гитхабовский линт всё равно пишет про ошибки
У меня сейчас линт проходит, и коммитить мне нечего

2023-11-09 11:30 UTC, mimalakhov commented
> там написан окакой файл reformatted app/routers/workplace.py

Я запускал pre-commit перед обоими коммитами, но гитхабовский линт всё равно пишет про ошибки
У меня сейчас линт проходит, и коммитить мне нечего

2023-11-10 07:40 UTC, merged