Add name for user + search fix
ProgramEngineeringOurJira/Backend pull request #15
Opened 2023-11-15 17:53 UTC by mimalakhov

Добавлено поле имени для пользователя
Соответственно, поправил поиск пользователя (теперь он идёт по имени)
Пул реквест для search я удалил

2023-11-17 18:50 UTC, Nicialy requested changes

2023-11-17 18:50 UTC, Nicialy commented on app/routers/search.py
> +    "/{workplace_id}/search/userissues",
/ добавить

2023-11-17 18:50 UTC, Nicialy commented on app/routers/search.py
> +    workplace_id: UUID = Path(...), start_str: SearchModel = Body(...), user: UserAssignedWorkplace = Depends(member)
start_str на более говорящее название заменить

2023-11-17 18:50 UTC, Nicialy commented on app/schemas/documents.py
> +    name: str = Field(default_factory=str)
убрать default_facctory

2023-11-17 18:50 UTC, Nicialy commented on app/routers/search.py
> +    workplace_id: UUID = Path(...), start_str: SearchModel = Body(...), user: UserAssignedWorkplace = Depends(member)
заменить поиск на gets

2023-11-19 07:55 UTC, mimalakhov commented
Андрей: сделай модель для строку поиска, чтобы фронту было понятно
Также Андрей: убери модель из запроса, чтобы был get-запрос

2023-11-21 09:23 UTC, Nicialy requested changes

2023-11-21 09:23 UTC, Nicialy commented on app/routers/search.py
> +@router.post(
change on get

2023-11-21 09:23 UTC, Nicialy commented on app/routers/search.py
> +@router.get(
Это типа мои issues?

2023-11-21 09:23 UTC, Nicialy commented on app/routers/search.py
> +@router.post(
get

2023-11-21 09:23 UTC, Nicialy commented on app/routers/search.py
> +    workplace_id: UUID = Path(...), searching_string: str = Path(...), user: UserAssignedWorkplace = Depends(member)
это не Path a Query

2023-11-21 09:23 UTC, Nicialy commented on app/routers/search.py
> +        RegEx(UserAssignedWorkplace.user.name, f"^{searching_string}"),
убрать f строку у тебя сама переменная str

2023-11-21 09:23 UTC, Nicialy commented on app/routers/search.py
> +        Issue.workplace.id == workplace_id, RegEx(Issue.name, f"^{searching_string}"), fetch_links=True
убрать f строку у тебя сама переменная str

2023-11-21 09:23 UTC, Nicialy commented on app/routers/search.py
> +    issues = await Issue.find(Issue.workplace.id == workplace_id, fetch_links=True).to_list()
Почему 53 стркоа отдельна, сюда в пихни поиск что implements = user

2023-11-21 09:23 UTC, Nicialy commented on app/routers/search.py
> +    user_issues = [i for i in issues if user in i.implementers]
Убрать

2023-11-21 09:23 UTC, Nicialy commented on app/routers/workplace.py
> +    prefix_email: str | None = "", workplace_id: UUID = Path(...), user: UserAssignedWorkplace = Depends(guest)
![image](https://github.com/ProgramEngineeringOurJira/Backend/assets/43730314/d326c088-96dd-4a0c-b310-dfa41e2db048)
отсюда тожк f-строку убрать

2023-11-21 09:23 UTC, Nicialy commented on app/routers/workplace.py
> +    prefix_email: str | None = "", workplace_id: UUID = Path(...), user: UserAssignedWorkplace = Depends(guest)
если без f-строки не как то , пиши на чистом mongo like:
 users = await User.find_many({"full_name": {"$regex": name, "$options": "-i"}}).to_list()

2023-11-21 12:16 UTC, mimalakhov commented on app/routers/search.py
> +@router.get(
Это типа все задачи в данном воркплейсе, которые начинаются с какой-то строки
По сути, поиск задачи

2023-11-21 12:32 UTC, mimalakhov commented on app/routers/workplace.py
> +    prefix_email: str | None = "", workplace_id: UUID = Path(...), user: UserAssignedWorkplace = Depends(guest)
Чем f-строка не нравится? Мне же ещё надо на воркплейс проверять в запросе
У Виталия в задаче сделано с find и f-строкой, и всё норм

2023-11-21 13:01 UTC, mimalakhov commented on app/routers/search.py
> +    issues = await Issue.find(Issue.workplace.id == workplace_id, fetch_links=True).to_list()
Так не работает
У нас implementers - это список, и проверить в find на то, есть ли пользователь в этом списке, никак нельзя

2023-11-21 13:13 UTC, mimalakhov commented on app/routers/workplace.py
> +    prefix_email: str | None = "", workplace_id: UUID = Path(...), user: UserAssignedWorkplace = Depends(guest)
А в mongodb я как буду регулярное выражение писать?
i - это опция для нечувствительности к регистру
Как я пропишу ^{searching_string}?

2023-11-25 18:06 UTC, closed without merging

2023-11-25 18:06 UTC, Nasochec commented
перекат в другой
https://github.com/ProgramEngineeringOurJira/Backend/pull/17