Sprints
ProgramEngineeringOurJira/Backend pull request #2
Opened 2023-09-24 20:33 UTC by Nasochec

Добавлена авторизация.
Почти реализованы ручки для спринтов, осталось сделать get для списка спринтов, а также проверку существования проекта при создании спринта.

2023-09-25 09:39 UTC, Nicialy requested changes

2023-09-25 09:39 UTC, Nicialy commented on app/auth/oauth2.py
> +    def __init__(self, role: Role):
тип List[Role]

2023-09-25 09:39 UTC, Nicialy commented on app/auth/oauth2.py
> +admin: RoleChecker = RoleChecker(Role.ADMIN)
[Role.ADMIN]

2023-09-25 09:39 UTC, Nicialy commented on app/auth/oauth2.py
> +        raise ForbiddenException
вроде ForbiddenException без () ошибку 500 даст

2023-09-25 09:39 UTC, Nicialy commented on app/routers/sprint/router.py
> +@router.post("/{workplace_id}/createsprint", response_model=SuccessfulResponse, status_code=status.HTTP_200_OK)
status.HTTP_201

2023-09-25 09:39 UTC, Nicialy commented on app/routers/sprint/router.py
> +@router.post("/{workplace_id}/createsprint", response_model=SuccessfulResponse, status_code=status.HTTP_200_OK)
/createsprint -> /sptints

2023-09-25 09:39 UTC, Nicialy commented on app/routers/sprint/router.py
> +async def create(
create_sprint

2023-09-25 09:39 UTC, Nicialy commented on app/routers/sprint/router.py
> +async def get(sprint_id: UUID = Path(...), user: User = Depends(guest)):
get_sprint

2023-09-25 09:39 UTC, Nicialy commented on app/routers/sprint/router.py
> +async def edit(sprint_creation: SprintCreation = Body(...), sprint_id: UUID = Path(...), user: User = Depends(admin)):
edit_sprint

2023-09-25 09:39 UTC, Nicialy commented on app/routers/sprint/router.py
> +async def delete(sprint_id: UUID = Path(...), user: User = Depends(admin)):
delete_sprint

2023-09-25 09:39 UTC, Nicialy commented on app/routers/sprint/router.py
> +@router.delete("/{workplace_id}/sprints/{sprint_id}", response_model=SuccessfulResponse, status_code=status.HTTP_200_OK)
status.HTTP_204

2023-09-25 09:39 UTC, Nicialy commented on app/routers/sprint/router.py
> +    return SuccessfulResponse()
убрать

2023-09-25 09:39 UTC, Nicialy commented on app/routers/sprint/router.py
> +    sprint.delete()
await не должно быть?

2023-09-25 09:39 UTC, Nicialy commented on app/routers/sprint/schemas.py
> +class SuccessfulResponse(BaseModel):
брать его из routers.auth

2023-09-25 09:39 UTC, Nicialy commented on app/routers/sprint/schemas.py
> +    id: UUID = Field(default=uuid4())
Вроде как должен быть _id проверь монгу есть ли id and _id у созданного спринта

2023-09-25 09:45 UTC, Nasochec commented on app/routers/sprint/schemas.py
> +    id: UUID = Field(default=uuid4())
Работает с id

2023-09-25 13:30 UTC, Nicialy requested changes

2023-09-25 13:30 UTC, Nicialy commented on app/routers/sprint/router.py
> +async def get_sprints(workplace_id: UUID = Path(...), user: User = Depends(guest), skip: int = 0, limit: int = 20):
Добавь skip limit в Path явно

2023-09-25 13:32 UTC, Nicialy requested changes

2023-09-25 13:32 UTC, Nicialy commented on app/auth/oauth2.py
> +        raise ForbiddenException("Не авторизован.")
Нет прав

2023-09-26 15:32 UTC, Nicialy requested changes

2023-09-26 15:32 UTC, Nicialy commented on app/routers/sprint/router.py
> +    sprint.__dict__.update(sprint_creation.model_dump())
__dict__ нетрогай

2023-09-26 15:32 UTC, Nicialy commented on app/routers/sprint/schemas.py
> +    async def validate_date_no_intersection(self):
Зачем 4 ифа, сделай один запрос и вынеси лоигку проверки в саму ручку одним запросом

2023-09-26 15:32 UTC, Nicialy commented on app/routers/sprint/schemas.py
> +    async def validate_date_no_intersection(self):
и выкидывай 400 а не 422

2023-09-26 18:55 UTC, Nicialy commented
Всё супер щас dev подправлю

2023-09-26 21:37 UTC, merged