Worksplaces
ProgramEngineeringOurJira/Backend pull request #4
Opened 2023-09-29 17:04 UTC by vital228

CRUD Workplace

2023-09-30 18:54 UTC, Nicialy commented
пока линт не пройдет не приму

2023-09-30 19:16 UTC, Nicialy requested changes

2023-09-30 19:16 UTC, Nicialy commented on app/routers/workplace/schemas.py
> +class SuccessfulResponse(BaseModel):
Брать из auth

2023-09-30 19:16 UTC, Nicialy commented on app/routers/workplace/schemas.py
> +    list_of_states: List[str] = Field(default=["Backlog", "To do", "In Progress", "In Review", "QA", "Done"])
просто states

2023-09-30 19:16 UTC, Nicialy commented on app/routers/workplace/schemas.py
> +    id: UUID = Field(default_factory=uuid4)
Вроде скобки должно быть, но если робит и так то ок

2023-09-30 19:16 UTC, Nicialy commented on app/routers/workplace/schemas.py
> +    id: UUID = Field(default_factory=uuid4)
uuid4()

2023-09-30 19:16 UTC, Nicialy commented on app/routers/workplace/router.py
> +    for userAssignedWorkplace in userAssignedWorkplaces:
переписать удаление в одну строчку  like: await Product.find(Product.category.name == "Chocolate").delete()

2023-09-30 19:16 UTC, Nicialy commented on app/routers/workplace/router.py
> +    for userAssignedWorkplace in userAssignedWorkplaces:
есть удаление с link

2023-09-30 19:16 UTC, Nicialy commented on app/routers/workplace/schemas.py
> +class Workplace(Document, WorkplaceCreation):
Добавить list[link[UserAssignedWorkplace]]
https://beanie-odm.dev/tutorial/relations/

2023-09-30 19:16 UTC, Nicialy commented on app/routers/workplace/router.py
> +    userAssignedWorkplace = UserAssignedWorkplace(user_id=user.id, workplace_id=workplace.id, role=Role.ADMIN)
создать через link

2023-10-01 15:13 UTC, vital228 commented on app/routers/workplace/schemas.py
> +    id: UUID = Field(default_factory=uuid4)
factory - это вызываемый метод.

2023-10-03 15:51 UTC, Nicialy commented
папку UserAssignedWorkplace удали

2023-10-03 15:52 UTC, Nicialy commented
и в документе UserAssignedWorkplace сделай link на Users и убери worksplace_id

2023-10-04 15:24 UTC, merged