CRUD issue. (un)assign user to issue. bug fix auth
ProgramEngineeringOurJira/Backend pull request #5
Opened 2023-09-29 18:21 UTC by Nasochec

CRUD Issue.
Назначение задач пользователю.
Оптимизация запросов к бд.
Исправления ошибки в авторизации.

2023-09-30 19:05 UTC, Nicialy commented
линтер true

2023-09-30 19:56 UTC, Nicialy requested changes

2023-09-30 19:56 UTC, Nicialy commented on app/routers/issue/schemas.py
> +class Issue(Document, IssueCreation):
Добавить исполнителей список юезров
Также List[Link] комментариев(сделать ее  отдельным документом (время, текст,List[photo_url]))

2023-09-30 19:56 UTC, Nicialy commented on app/routers/issue/router.py
> +    # TODO запрос к бд, что указанный статус есть в ворплейсе
надо слить вас с виталием

2023-09-30 19:56 UTC, Nicialy commented on app/routers/sprint/router.py
> +    find_sprint = await Sprint.find_one(
сделать поиск только в workplace with кокнретным id

2023-09-30 19:56 UTC, Nicialy commented on app/routers/user_assigned_issue/router.py
> +    "/{workplace_id}/issues/{issue_id}/users/{user_id}",
{user_id} - убрать

2023-09-30 19:56 UTC, Nicialy commented on app/routers/user_assigned_issue/router.py
> +    user_id: PydanticObjectId = Path(...),
сделать body list users_id

2023-09-30 19:56 UTC, Nicialy commented on app/routers/user_assigned_issue/router.py
> +    user = await User.find_one(User.id == user_id)
выбрать другое название переменной так как ты перекрываешь переменную вы в 28 строке

2023-09-30 19:56 UTC, Nicialy commented on app/routers/user_assigned_issue/router.py
> +    user_id: PydanticObjectId = Path(...),
и для нее в проверке юзнуть лямбдо выражение на проверку и выкинуть ошибку если хотя одного нет

2023-09-30 19:56 UTC, Nicialy commented on app/routers/user_assigned_issue/router.py
> +        raise ValidationError("Данный пользователь уже назаначен к этой задаче.")
36-47 заменим с помощью виталия
он workplace свяжет по Link с userASsignedWorplace и ты проверишь workplace получишь его с списком юзеров  и дальше через map проверишь роль
ошибка что юзер уже привязан можно не выкидывать там вроде как не должно быть ошибки при создании f если есть, то навреное есть игнор этого

2023-09-30 19:56 UTC, Nicialy commented on app/routers/user_assigned_issue/router.py
> +@router.get("/{workplace_id}/issues/{issue_id}/users", response_model=List[User], status_code=status.HTTP_200_OK)
cделать вывод юзеров к задаче в самой задаче ,связав задачу с назначенными юзерами

2023-09-30 19:56 UTC, Nicialy commented on app/routers/user_assigned_issue/router.py
> +    "/{workplace_id}/issues/{issue_id}/users/{user_id}", response_model=None, status_code=status.HTTP_204_NO_CONTENT
ух, похоже лучше запихнуть все ветку assignedusersIssue в cамо issue. Слишком много запросов на одну связанную логику. delete assigned users будет в put users

2023-09-30 19:56 UTC, Nicialy commented on app/routers/user_assigned_issue/router.py
> +    "/{workplace_id}/issues/{issue_id}/users/{user_id}", response_model=None, status_code=status.HTTP_204_NO_CONTENT
Да лучше все эти ручки в issues

2023-09-30 19:56 UTC, Nicialy commented on app/routers/user_assigned_issue/schemas.py
> +class UserAssignedIssue(Document):
Валидацию можно впихнуть в документ он может делать async запросы

2023-09-30 19:56 UTC, Nicialy commented on app/routers/issue/schemas.py
> +class Issue(Document, IssueCreation):
https://beanie-odm.dev/tutorial/relations/

2023-10-04 15:40 UTC, Nasochec commented on app/routers/issue/schemas.py
> +class Issue(Document, IssueCreation):
Не список пользователей, а список их id. (чтобы пользователи не удалялись при удалении задачи)
Список Комментариев - отдельная задаче, будет выполняться позже.

2023-10-04 15:41 UTC, Nasochec commented on app/routers/issue/router.py
> +    # TODO запрос к бд, что указанный статус есть в ворплейсе
слил

2023-10-07 18:43 UTC, Nasochec commented
В последнем коммите сделаны Задачи, спринты, проекты и всё подвязано с помошью links. 
Код похож на говнокод, да он им и является. С линками по другому ни как. Криворукий лох, прописывавший линки не подумал, что было бы неплохо иметь возможность выбрать удалять привязанный элемент или нет. 
Также криворукий лох, который прописывал бэклинки не подумал, что могло бы быть полезно выбрать возможность не УДАЛИТЬ ЭЛЕМЕНТ, а удалить саму ссылку из другого документа.

Как по мне лучше вернуться к варианту без линков. На самом деле запросов к БД так станет меньше и они станут проще. Если кто-то считает что сделает лучше - пожалуйста, я умываю руки.

2023-10-16 03:55 UTC, merged