CRUD comment. security fix
ProgramEngineeringOurJira/Backend pull request #8
Opened 2023-10-22 10:03 UTC by Nasochec

https://app.plane.so/program-engineering/projects/f23a2db8-c80e-4d8e-bdd3-7be8ff8b56fe/issues/1361b1dd-140e-4236-8937-7c873a2c04c4
https://app.plane.so/program-engineering/projects/f23a2db8-c80e-4d8e-bdd3-7be8ff8b56fe/issues/cea11065-05ce-4546-b421-872dc3646946

2023-10-26 19:19 UTC, Nasochec commented
АНДРЕЙ ЛОХ НЕ ПРОВЕРЯЕТ ПУЛ РЕКВЕСТ.

2023-10-28 15:37 UTC, Nicialy commented
Да проверю я

2023-10-28 15:41 UTC, Nicialy requested changes

2023-10-28 15:41 UTC, Nicialy commented on app/schemas/models/comment.py
> +    files: Optional[List[UUID]]
str

2023-10-28 15:41 UTC, Nicialy commented on app/schemas/models/comment.py
> +    files: List[UUID] = Field(default=list())
str

2023-10-28 15:41 UTC, Nicialy commented on app/schemas/documents.py
> +        if self.sprint is not None:
к сожалению None не робит в BackLinks ;(

2023-10-28 15:41 UTC, Nicialy commented on app/schemas/models/comment.py
> +    files: List[UUID] = Field(default=list())
это ссылка на файл

2023-10-28 15:41 UTC, Nicialy commented on app/schemas/models/comment.py
> +    files: List[UUID] = Field(default=list())
List[str]*

2023-10-28 15:41 UTC, Nicialy commented on app/routers/comment.py
> +    await comment.update({"$set": comment_creation.model_dump(exclude="files")})
включи files

2023-10-28 16:10 UTC, Nasochec commented on app/schemas/documents.py
> +        if self.sprint is not None:
да, тем не менее, те  действия должны проводиться если sprint не None,

2023-11-08 18:34 UTC, merged